# based on https://towardsaws.com/build-push-docker-image-to-aws-ecr-using-github-actions-8396888a8f9e

name: Build and deploy R Lambda Docker image to ECR

# update the image whenever we touch the the lambda branch
on:
  workflow_dispatch:
  push:
    branches: lambda
    # paths:
    #   - "/.github/workflows/build-upload-docker.yml"
    #   - "/lambda/createPlots/*"

jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest

    steps:

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        mask-password: true

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: iihrn-create-plots
        IMAGE_TAG: latest
      run: |
        cd lambda/createPlots
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
